### ISSUE TITLE
Parent & Child Category dropdown

### ISSUE THREAD

**Issue by CreativesGuild** [timothyjensen/gravityformsadvancedselect#1]
Hi Timothy, 

Love the plugin and works exactly like I need it - just want to know if there is a way to have parent and child categories display as an accordion, initial state collapsed?

**Comment by timothyjensen** [comment]
There is not currently a way to display the items in an accordion. The plugin uses Tom Select under the hood, so you might check their documentation to see if you find anything that could work for you, in particular the [customization section](https://tom-select.js.org/examples/customization/).
