### ISSUE TITLE
multiple form in one page problem

### ISSUE THREAD

**Issue by fariborzasgarpour** [timothyjensen/gravityformsadvancedselect#4]
Hello
Thanks for this great plugin
There is a problem when we have 2 forms on the same page and this plugin is used in its fields
We get a JavaScript mismatch problem and an error
![image](https://github.com/timothyjensen/gravityformsadvancedselect/assets/53476655/6fa82ae5-f6a0-453b-9218-20d8aa2b1a2b)

**Comment by timothyjensen** [comment]
Thanks for reporting this problem. The issue is resolved in version 0.2.5.
